CaseManagement/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Plan</label>
        <referenceTo>Case_Plan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Admin</fullName>
        <active>true</active>
        <businessProcess>Admin</businessProcess>
        <label>Admin</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

CaseManagement/src/objects/Case_Plan__c.object
<CustomObject>
    <fields>
        <fullName>CaseStatusOrdering__c</fullName>
        <label>Case Status Ordering</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>Record Type Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType_SupportProcess__c</fullName>
        <label>Record Type / Support Process</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Plan</label>
    <nameField>
        <label>Case Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CaseManagement/src/objects/Case_Step__c.object
<CustomObject>
    <fields>
        <fullName>Associated_Status__c</fullName>
        <label>Associated Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Steps</relationshipLabel>
        <relationshipName>Case_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flow_By_User__c</fullName>
        <label>Flow By User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsCompleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsCompleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Pending__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Pending</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PlanStepOrder__c</fullName>
        <label>PlanStepOrderDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Plan_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Step</label>
        <referenceTo>Plan_Step__c</referenceTo>
        <relationshipLabel>Case Steps</relationshipLabel>
        <relationshipName>Case_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Step</label>
    <nameField>
        <label>Case Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Step__c.object
    <fields>
        <fullName>Associate_Case_Status__c</fullName>
        <label>Associate Case Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/objects/Case_Step__c.object
    <fields>
        <fullName>Case_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Plan</label>
        <referenceTo>Case_Plan__c</referenceTo>
        <relationshipLabel>Case Steps</relationshipLabel>
        <relationshipName>Case_Steps</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/Case_Step__c.object
    <fields>
        <fullName>Flow__c</fullName>
        <label>Flow</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/objects/Case_Step__c.object
    <fields>
        <fullName>Is_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>

src/objects/Case_Step__c.object
    <fields>
        <fullName>Start_When__c</fullName>
        <label>Start_When__c</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Send Reports To Client</fullName>
                </value>
                <value>
                    <fullName>Request Reports</fullName>
                </value>
                <value>
                    <fullName>Wait For Approval</fullName>
                </value>
                <value>
                    <fullName>Account Setup</fullName>
                </value>
                <value>
                    <fullName>Create Account</fullName>
                </value>
                <value>
                    <fullName>Create Contact</fullName>
                </value>
                <value>
                    <fullName>Send Email</fullName>
                </value>
                <value>
                    <fullName>Test Case Step Internal</fullName>
                </value>
                <value>
                    <fullName>Test Step</fullName>
                </value>
                <value>
                    <fullName>Update Opportunity</fullName>
                </value>
                <value>
                    <fullName>Update Opportunity Status</fullName>
                </value>
                <value>
                    <fullName>create Refresh</fullName>
                </value>
                <value>
                    <fullName>test user Step</fullName>
                </value>
                <value>
                    <fullName>Case Step Testing</fullName>
                </value>
                <value>
                    <fullName>Direct User</fullName>
                </value>
                <value>
                    <fullName>Test New Flow</fullName>
                </value>
                <value>
                    <fullName>Test 2</fullName>
                </value>
                <value>
                    <fullName>Test Case Step</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>xyz</fullName>
                </value>
                <value>
                    <fullName>Update Contact</fullName>
                </value>
                <value>
                    <fullName>Test User 2</fullName>
                </value>
                <value>
                    <fullName>Test User</fullName>
                </value>
                <value>
                    <fullName>Add User To Public Group</fullName>
                </value>
                <value>
                    <fullName>Wait For User Response</fullName>
                </value>
                <value>
                    <fullName>Create Community User</fullName>
                </value>
                <value>
                    <fullName>Create User</fullName>
                </value>
                <value>
                    <fullName>Manager Approval</fullName>
                </value>
                <value>
                    <fullName>IT Approvals</fullName>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

CaseManagement/src/force-app/main/default/objects/Plan_Step__c.object
<CustomObject>
    <fields>
        <fullName>Associate_Case_Status__c</fullName>
        <label>Associate Case Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Plan</label>
        <referenceTo>Case_Plan__c</referenceTo>
        <relationshipLabel>Plan Steps</relationshipLabel>
        <relationshipName>Plan_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flow__c</fullName>
        <label>Flow</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_When__c</fullName>
        <label>Start_When__c</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Step 2</fullName>
                </value>
                <value>
                    <fullName>Step1</fullName>
                </value>
                <value>
                    <fullName>st1</fullName>
                </value>
                <value>
                    <fullName>Clear Record</fullName>
                </value>
                <value>
                    <fullName>Wait For Approval</fullName>
                </value>
                <value>
                    <fullName>Send Approval Request</fullName>
                </value>
                <value>
                    <fullName>Create Contact</fullName>
                </value>
                <value>
                    <fullName>Create Account</fullName>
                </value>
                <value>
                    <fullName>Send Email</fullName>
                </value>
                <value>
                    <fullName>Create User</fullName>
                </value>
                <value>
                    <fullName>Create Account`</fullName>
                </value>
                <value>
                    <fullName>Send Email Test Button Width ABCDEF</fullName>
                </value>
                <value>
                    <fullName>asdfasdf</fullName>
                </value>
                <value>
                    <fullName>TestAdmin1</fullName>
                </value>
                <value>
                    <fullName>JD Step 1SD</fullName>
                </value>
                <value>
                    <fullName>NewTestStep</fullName>
                </value>
                <value>
                    <fullName>JDtest sttep</fullName>
                </value>
                <value>
                    <fullName>JDStep1</fullName>
                </value>
                <value>
                    <fullName>JDTest Step 1</fullName>
                </value>
                <value>
                    <fullName>Test Step 1 Case Plan 1</fullName>
                </value>
                <value>
                    <fullName>Test Plan</fullName>
                </value>
                <value>
                    <fullName>SD new Steps 1</fullName>
                </value>
                <value>
                    <fullName>SD New Steps</fullName>
                </value>
                <value>
                    <fullName>SD New Plan Step</fullName>
                </value>
                <value>
                    <fullName>JD Step 2</fullName>
                </value>
                <value>
                    <fullName>Step 3</fullName>
                </value>
                <value>
                    <fullName>Step 1</fullName>
                </value>
                <value>
                    <fullName>Test Case Step new Flow</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Plan Step</label>
    <nameField>
        <label>Plan Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan_Step__c.object
    <fields>
        <fullName>Case_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Step</label>
        <referenceTo>Case_Step__c</referenceTo>
        <relationshipLabel>Plan Steps</relationshipLabel>
        <relationshipName>Plan_Steps</relationshipName>
        <type>Lookup</type>
    </fields>

CaseManagement/CaseManagement/force-app/main/default/classes/CaseMgmt_CasePlanController.cls
global class CaseMgmt_CasePlanController {

/********************************************************
Controller for CaseMgmt_CasePlan lightning component
*********************************************************/
    
    @auraEnabled
    public static CaseManager manageCase(Id recordId){
        
        CaseManager caseManagerRecord = new CaseManager();
        caseStepWrapper caseStepWrpobj;
        List<Plan_Step__c> planStepList = new List<Plan_Step__c>();
        //Map<Plan_Step__c,Case_Step__c> planStepAndCaseStepMap = new Map<Plan_Step__c, Case_Step__c>();
        List<Case_Step__c> caseStepList = new List<Case_Step__c>();
        Boolean flag = false;
        // Fetch Case Plans and Status From Case on the basis of recordId come from component
        List<Case> caseRecords = new List<Case>([Select Id, Status,Case_Plan__c  From Case where Id =: recordId]);
        if(!caseRecords.isEmpty()){
            caseManagerRecord.CaseStatus = caseRecords[0].Status;
        }
        // Retrive all Plan_Steps Which have current case status and caseId, to create a wrapper and add fields according to case plan Where Case Plan Not Null and Equals to Case's Associated Case Plan
        // Associated Case Status Should be case's current status
        for(Plan_Step__c planStepObject : [Select Id, Name, Flow__c, Start_When__c, Associate_Case_Status__c, Is_Required__c From Plan_Step__c Where Case_Plan__c =: caseRecords[0].Case_Plan__c AND Associate_Case_Status__c =: caseRecords[0].Status ORDER BY CreatedDate ASC]){
            planStepList.add(planStepObject);
        }
        // Retrive all Case Steps associated with caseId and Plan Step  to create a wrapper and add fields according to case plan and Plan steps where case plan relate to case
        // Associated Flow can be null for Case Step if admin create it, if user creates it then it should contain flow name
        // Case Plan Shuld be related to Plan Steps which is Associate to Case Plan And Associate Status is Case Current Status,
        for(Case_Step__c caseStepObjt : [Select Id, Name,PlanStepOrder__c, IsCompleted__c, Is_Pending__c,Associated_Status__c,Flow_By_User__c, Case__c, Plan_Step__c From Case_Step__c Where Case__c =: recordId AND (Flow_By_User__c != null OR Plan_Step__c IN : planStepList) AND Associated_Status__c =: caseRecords[0].Status  ORDER BY PlanStepOrder__c ASC]){

            caseStepList.add(caseStepObjt);
        }
        // Check Case Step is Created by user or Admin and update wrapper according to user and admin.
        for(Case_Step__c caseStepObject : caseStepList){
            flag = false;
            for(Plan_Step__c planStepObj : planStepList){
                if(caseStepObject.Plan_Step__c == planStepObj.Id && !flag){
                    caseStepWrpobj = new caseStepWrapper();
                    caseStepWrpobj.StepName =  planStepObj.Name;
                    caseStepWrpobj.AssociateStatus = planStepObj.Associate_Case_Status__c;
                    caseStepWrpobj.IsRequired   = planStepObj.Is_Required__c;
                    caseStepWrpobj.StepFlow = planStepObj.Flow__c;
                    caseStepWrpobj.PlanStepId = planStepObj.Id;
                    caseStepWrpobj.StartWhen = planStepObj.Start_When__c;
                    caseStepWrpobj.CaseStepId = caseStepObject.Id;
                    caseStepWrpobj.IsCompleted = caseStepObject.IsCompleted__c;
                    caseStepWrpobj.IsPending = caseStepObject.Is_Pending__c;
                    caseManagerRecord.caseStepWraperList.add(caseStepWrpobj);
                    flag = true;
                }
            }
            if(!flag){
                caseStepWrpobj = new caseStepWrapper();
                caseStepWrpobj.StepName =  caseStepObject.Name;
                caseStepWrpobj.AssociateStatus = caseStepObject.Associated_Status__c;
                caseStepWrpobj.IsRequired   = false;
                caseStepWrpobj.StepFlow = caseStepObject.Flow_By_User__c;
                caseStepWrpobj.PlanStepId = null;
                caseStepWrpobj.StartWhen = 'None';
                caseStepWrpobj.CaseStepId = caseStepObject.Id;
                caseStepWrpobj.IsCompleted = caseStepObject.IsCompleted__c;
                caseStepWrpobj.IsPending = caseStepObject.Is_Pending__c;
                caseManagerRecord.caseStepWraperList.add(caseStepWrpobj);
            }

        }
        // Fetch Case Plan Record Where Id of Case plan is Come from Case Associated Case Plan
        for(Case_Plan__c casepl : [SELECT Name, Id, CaseStatusOrdering__c, RecordType_SupportProcess__c, RecordTypeId__c FROM Case_Plan__c WHERE Id =: caseRecords[0].Case_Plan__c]){
            caseManagerRecord.recordCasePlan =casepl;
        }



        return caseManagerRecord;
    }
    
    
    @InvocableMethod
    public static List<String> fetchRecordTypePicklistValue(List<String> RecordIdList){
        List<String> orderStatusStringList = new List<String>();
        String sfdcURL = URL.getSalesforceBaseUrl().toExternalForm();
        String restAPIURL = sfdcURL + '/services/data/v45.0/ui-api/object-info/Case/picklist-values/' +RecordIdList[0];
        caseMgmt_JSON2Apex myWrapper;
        HttpRequest httpRequest = new HttpRequest();
        httpRequest.setMethod('GET');
        PageReference pg = new PageReference('/Apex/SessionIdUtilityPage');
        String sessionId ='';
        If(!test.isRunningTest()){
            sessionId = pg.getContent().toString().substringBetween('<div id="apiSeesionID">','</div>').trim();
        }

        httpRequest.setHeader('Authorization', 'OAuth ' + sessionId);
        System.debug('URL >>> ' + restAPIURL);
        httpRequest.setHeader('Authorization', 'Bearer ' + sessionId);
        httpRequest.setEndpoint(restAPIURL);
        String response = '';
        String orderString;
        try {
            If(!test.isRunningTest()){
                Http http = new Http();
                HttpResponse httpResponse = http.send(httpRequest);
                if (httpResponse.getStatusCode() == 200 ) {
                    response = JSON.serializePretty( JSON.deserializeUntyped(httpResponse.getBody()) );
                    caseMgmt_JSON2Apex selectedCse =  caseMgmt_JSON2Apex.parse(httpResponse.getBody());
                    List<caseMgmt_JSON2Apex.values> listOfStatus = selectedCse.picklistFieldValues.Status.Values;
                    for(caseMgmt_JSON2Apex.values value : listOfStatus){
                        if(orderString == null){
                            orderString = String.valueOf(value.value);
                        }else{
                            orderString = orderString + ',' + String.valueOf(value.value);
                        }
                    }
                    orderStatusStringList.add(orderString);
                } else {

                    throw new CalloutException( httpResponse.getBody() );
                }
            }
        } catch( System.Exception e) {
            
            throw e;
        }
        return orderStatusStringList;
    }
    
    public class CaseManager{
        @auraEnabled public List<CaseMgmt_CasePlanController.caseStepWrapper> caseStepWraperList;
        @auraEnabled public String CaseStatus;
        @auraEnabled public Case_Plan__c recordCasePlan;
        public CaseManager(){
            caseStepWraperList = new List<CaseMgmt_CasePlanController.caseStepWrapper>();
            CaseStatus = '';
            recordCasePlan = new Case_Plan__c();
        }
    }
    public class caseStepWrapper{
        @auraEnabled public String StepName;
        @auraEnabled public String StepFlow;
        @auraEnabled public Boolean IsPending;
        @auraEnabled public Boolean IsCompleted;
        @auraEnabled public Boolean IsRequired;
        @auraEnabled public String AssociateStatus;
        @auraEnabled public String CaseStepId;
        @auraEnabled public String PlanStepId;
        @auraEnabled public String StartWhen;
    }
}