src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Live_Call_Object__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Live Call Object</label>
        <referenceTo>Live_Call_Object__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Live_Call_Object__c.object
<CustomObject>
    <fields>
        <fullName>Cogito_User_ID__c</fullName>
        <label>Cogito User ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Live Call Object</label>
    <nameField>
        <label>Live Call Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Call Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Cogito_User_ID__c</fullName>
        <label>Cogito User ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/updateCallObjectTest.cls
@isTest
public class updateCallObjectTest {
    @isTest static void UnittestNewLiveCall(){
        user testUser=new user(id=userInfo.getUserId());
        testUser.Cogito_User_ID__c='Test';
        update testUser;
        
        Case testCase=new case();
        testCase.subject='Test Case';
        testCase.Priority='High';
        testCase.Origin='Phone';
        insert testCase;
    }
    
    @isTest static void UnittestExistingLiveCall(){
        user testUser=new user(id=userInfo.getUserId());
        testUser.Cogito_User_ID__c='Test';
        update testUser;
        
        Live_Call_Object__c LiveCall = new Live_Call_Object__c();
        LiveCall.Cogito_User_ID__c='Test';
        insert LiveCall;
        
        Case testCase=new case();
        testCase.subject='Test Case';
        testCase.Priority='High';
        testCase.Origin='Phone';
        insert testCase;
    }
}