src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Plan</label>
        <referenceTo>Case_Plan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Case_Plan__c.object
<CustomObject>
    <label>Case Plan</label>
    <nameField>
        <label>Case Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src - 26 March/objects/Case_Plan_Support_Process__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Case_Plan__c</fullName>
        <label>Case Plan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Support_Process__c</fullName>
        <label>RecordType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Plan &amp; Support Process</label>
</CustomObject>

src - 26 March/objects/Case_Step__c.object
<CustomObject>
    <fields>
        <fullName>Associated_Status__c</fullName>
        <label>Associated Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Steps</relationshipLabel>
        <relationshipName>Case_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PlanStepOrder__c</fullName>
        <label>PlanStepOrder</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Plan_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Step</label>
        <referenceTo>Plan_Step__c</referenceTo>
        <relationshipLabel>Case Steps</relationshipLabel>
        <relationshipName>Case_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Step</label>
    <nameField>
        <label>Case Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Step__c.object
    <fields>
        <fullName>Associate_Case_Status__c</fullName>
        <label>Associate Case Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/objects/Case_Step__c.object
    <fields>
        <fullName>Case_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Plan</label>
        <referenceTo>Case_Plan__c</referenceTo>
        <relationshipLabel>Case Steps</relationshipLabel>
        <relationshipName>Case_Steps</relationshipName>
        <type>Lookup</type>
    </fields>

src - 26 March/objects/Plan_Step__c.object
<CustomObject>
    <fields>
        <fullName>Associate_Case_Status__c</fullName>
        <label>Associate Case Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Plan</label>
        <referenceTo>Case_Plan__c</referenceTo>
        <relationshipLabel>Plan Steps</relationshipLabel>
        <relationshipName>Plan_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan Step</label>
    <nameField>
        <label>Plan Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan_Step__c.object
    <fields>
        <fullName>Case_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Step</label>
        <referenceTo>Case_Step__c</referenceTo>
        <relationshipLabel>Plan Steps</relationshipLabel>
        <relationshipName>Plan_Steps</relationshipName>
        <type>Lookup</type>
    </fields>

src - 26 March/classes/caseToAddCaseStepsTriggerHandler.cls
/**
* Created by Shubham on 2/21/2019.
*/

public with sharing class caseToAddCaseStepsTriggerHandler {


    public static void beforeInsertAndUpdate(List<Case> newList, Map<Id, Case> oldMap) {
        updateCasePlanWhenInsertAndUpdate(newList, oldMap);
    }
    public static void afterInsertAndUpdate(List<Case> newList, Map<Id, Case> oldMap) {
        updateCaseSteps(newList, oldMap);
    }
    public static void updateCaseSteps(List<Case> newList, Map<Id, Case> oldMap) {
        Set<Id> casePlanIdSet = new Set<Id>();
        Map<Id, List<Plan_Step__c>> mapOfCasePlanIdWithPlanSteps = new Map<Id, List<Plan_Step__c>>();
        List<Case_Step__c> listOfCaseSteptoBeCreated = new List<Case_Step__c>();
        Set<Id> CaseIdSet = new Set<Id>();
        Case_Step__c caseStepObj;
        List<Case> newListCase = new List<Case>();
        List<Case_Step__c> caseStepToBeDeleted = new List<Case_Step__c>();

        for (Case caseObj : newList) {
            if(oldMap == null){
                casePlanIdSet.add(caseObj.Case_Plan__c);
                newListCase.add(caseObj);
            }else{
                if(oldMap.get(caseObj.Id).RecordTypeId != caseObj.RecordTypeId){
                    casePlanIdSet.add(caseObj.Case_Plan__c);
                    newListCase.add(caseObj);
                    CaseIdSet.add(caseObj.Id);
                }
            }
        }

        for(Case_Step__c caseStepLoopObj : [Select Id from Case_Step__c Where Case__c IN : CaseIdSet]){
            caseStepToBeDeleted.add(caseStepLoopObj);
        }

        if(caseStepToBeDeleted.size() > 0){
            delete caseStepToBeDeleted;
        }

        for (Plan_Step__c planStep : [Select Id, Name,Case_Plan__c, Associate_Case_Status__c,CreatedDate from Plan_Step__c Where Case_Plan__c IN :casePlanIdSet]) {
            if (mapOfCasePlanIdWithPlanSteps.containsKey(planStep.Case_Plan__c)) {
                mapOfCasePlanIdWithPlanSteps.get(planStep.Case_Plan__c).add(planStep);
            } else {
                mapOfCasePlanIdWithPlanSteps.put(planStep.Case_Plan__c, new List<Plan_Step__c>{
                        planStep
                });
            }
        }

        for (Case caseobj : newListCase){
            for(Id casePlanId : mapOfCasePlanIdWithPlanSteps.keySet()){
                if(casePlanId == caseobj.Case_Plan__c){
                    for(Plan_Step__c planStep : mapOfCasePlanIdWithPlanSteps.get(casePlanId)){
                        caseStepObj = new Case_Step__c();
                        caseStepObj.Name = planStep.Name;
                        caseStepObj.Case__c = caseobj.Id;
                        caseStepObj.Plan_Step__c = planStep.Id;
                        caseStepObj.PlanStepOrder__c = planStep.CreatedDate;
                        caseStepObj.Associated_Status__c = planStep.Associate_Case_Status__c;
                        listOfCaseSteptoBeCreated.add(caseStepObj);
                    }
                }
            }
        }

        if(listOfCaseSteptoBeCreated.size() > 0){
            insert listOfCaseSteptoBeCreated;
        }



    }
    public static void updateCasePlanWhenInsertAndUpdate(List<Case> newList, Map<Id, Case> oldMap) {
        Map<String, String> mapOfActiveCasePlanWithRecordType = new Map<String, String>();
        List<RecordType> recordTypelist = new List<RecordType>();
        Map<String, String> mapOfCasePlanNameWithId = new Map<String, String>();
        for (Case_Plan_Support_Process__c casePlanSupportProcess : [Select Id, Case_Plan__c, Support_Process__c From Case_Plan_Support_Process__c]) {
            mapOfActiveCasePlanWithRecordType.put(casePlanSupportProcess.Support_Process__c, casePlanSupportProcess.Case_Plan__c);
        }
        for (RecordType recordTypeRec : [Select Id, DeveloperName from RecordType where SobjectType = 'Case']) {
            recordTypelist.add(recordTypeRec);
        }
        for (Case_Plan__c casePlan : [Select Id, Name from Case_Plan__c Where Name IN :mapOfActiveCasePlanWithRecordType.values()]) {
            mapOfCasePlanNameWithId.put(casePlan.Name, casePlan.Id);
        }
        if (oldMap == null) {
            for (case casObj : newList) {
                if (casObj.RecordTypeId != null) {
                    for (RecordType recObj : recordTypelist) {
                        if (casObj.RecordTypeId == recObj.Id) {
                            casObj.Case_Plan__c = mapOfCasePlanNameWithId.get(mapOfActiveCasePlanWithRecordType.get(recObj.DeveloperName));
                        }
                    }

                }
            }
        } else {
            for (Id oldCaseid : oldMap.keySet()) {
                for (Case caseObj : newList) {
                    if (caseObj.RecordTypeId != oldMap.get(oldCaseid).RecordTypeId) {
                        for (RecordType recObj : recordTypelist) {
                            if (caseObj.RecordTypeId == recObj.Id) {
                                caseObj.Case_Plan__c = mapOfCasePlanNameWithId.get(mapOfActiveCasePlanWithRecordType.get(recObj.DeveloperName));
                            }
                        }
                    }
                }
            }

        }
    }


}