src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Plan</label>
        <referenceTo>Case_Plan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Case_Plan__c.object
<CustomObject>
    <fields>
        <fullName>CaseStatusOrdering__c</fullName>
        <label>Case Status Ordering</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Plan</label>
    <nameField>
        <label>Case Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src - 26 March/objects/Case_Plan_Support_Process__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Case_Plan__c</fullName>
        <label>Case Plan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Plan &amp; Support Process</label>
</CustomObject>

src/objects/Case_Step__c.object
<CustomObject>
    <fields>
        <fullName>Associate_Case_Status__c</fullName>
        <label>Associate Case Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Plan</label>
        <referenceTo>Case_Plan__c</referenceTo>
        <relationshipLabel>Case Steps</relationshipLabel>
        <relationshipName>Case_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Steps</relationshipLabel>
        <relationshipName>Case_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flow__c</fullName>
        <label>Flow</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsCompleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsCompleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Pending__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Pending</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_When__c</fullName>
        <label>Start_When__c</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Send Reports To Client</fullName>
                </value>
                <value>
                    <fullName>Request Reports</fullName>
                </value>
                <value>
                    <fullName>Wait For Approval</fullName>
                </value>
                <value>
                    <fullName>Account Setup</fullName>
                </value>
                <value>
                    <fullName>Create Account</fullName>
                </value>
                <value>
                    <fullName>Create Contact</fullName>
                </value>
                <value>
                    <fullName>Send Email</fullName>
                </value>
                <value>
                    <fullName>Test Case Step Internal</fullName>
                </value>
                <value>
                    <fullName>Test Step</fullName>
                </value>
                <value>
                    <fullName>Update Opportunity</fullName>
                </value>
                <value>
                    <fullName>Update Opportunity Status</fullName>
                </value>
                <value>
                    <fullName>create Refresh</fullName>
                </value>
                <value>
                    <fullName>test user Step</fullName>
                </value>
                <value>
                    <fullName>Case Step Testing</fullName>
                </value>
                <value>
                    <fullName>Direct User</fullName>
                </value>
                <value>
                    <fullName>Test New Flow</fullName>
                </value>
                <value>
                    <fullName>Test 2</fullName>
                </value>
                <value>
                    <fullName>Test Case Step</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>xyz</fullName>
                </value>
                <value>
                    <fullName>Update Contact</fullName>
                </value>
                <value>
                    <fullName>Test User 2</fullName>
                </value>
                <value>
                    <fullName>Test User</fullName>
                </value>
                <value>
                    <fullName>Add User To Public Group</fullName>
                </value>
                <value>
                    <fullName>Wait For User Response</fullName>
                </value>
                <value>
                    <fullName>Create Community User</fullName>
                </value>
                <value>
                    <fullName>Create User</fullName>
                </value>
                <value>
                    <fullName>Manager Approval</fullName>
                </value>
                <value>
                    <fullName>IT Approvals</fullName>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Step</label>
    <nameField>
        <label>Case Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src - 26 March/objects/Case_Step__c.object
    <fields>
        <fullName>Plan_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Step</label>
        <referenceTo>Plan_Step__c</referenceTo>
        <relationshipLabel>Case Steps</relationshipLabel>
        <relationshipName>Case_Steps</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/Plan_Step__c.object
<CustomObject>
    <fields>
        <fullName>Case_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Plan</label>
        <referenceTo>Case_Plan__c</referenceTo>
        <relationshipLabel>Plan Steps</relationshipLabel>
        <relationshipName>Plan_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Step</label>
        <referenceTo>Case_Step__c</referenceTo>
        <relationshipLabel>Plan Steps</relationshipLabel>
        <relationshipName>Plan_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan Step</label>
    <nameField>
        <label>Plan Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src - 27 March/objects/Plan_Step__c.object
    <fields>
        <fullName>Associate_Case_Status__c</fullName>
        <label>Associate Case Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src - 27 March/objects/Plan_Step__c.object
    <fields>
        <fullName>Flow__c</fullName>
        <label>Flow</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src - 27 March/objects/Plan_Step__c.object
    <fields>
        <fullName>Is_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>

src - 27 March/objects/Plan_Step__c.object
    <fields>
        <fullName>Start_When__c</fullName>
        <label>Start_When__c</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Clear Record</fullName>
                </value>
                <value>
                    <fullName>Wait For Approval</fullName>
                </value>
                <value>
                    <fullName>Send Approval Request</fullName>
                </value>
                <value>
                    <fullName>Create Contact</fullName>
                </value>
                <value>
                    <fullName>Create Account</fullName>
                </value>
                <value>
                    <fullName>Send Email</fullName>
                </value>
                <value>
                    <fullName>Create User</fullName>
                </value>
                <value>
                    <fullName>Create Account`</fullName>
                </value>
                <value>
                    <fullName>Send Email Test Button Width ABCDEF</fullName>
                </value>
                <value>
                    <fullName>asdfasdf</fullName>
                </value>
                <value>
                    <fullName>TestAdmin1</fullName>
                </value>
                <value>
                    <fullName>JD Step 1SD</fullName>
                </value>
                <value>
                    <fullName>NewTestStep</fullName>
                </value>
                <value>
                    <fullName>JDtest sttep</fullName>
                </value>
                <value>
                    <fullName>JDStep1</fullName>
                </value>
                <value>
                    <fullName>JDTest Step 1</fullName>
                </value>
                <value>
                    <fullName>Test Step 1 Case Plan 1</fullName>
                </value>
                <value>
                    <fullName>Test Plan</fullName>
                </value>
                <value>
                    <fullName>SD new Steps 1</fullName>
                </value>
                <value>
                    <fullName>SD New Steps</fullName>
                </value>
                <value>
                    <fullName>SD New Plan Step</fullName>
                </value>
                <value>
                    <fullName>JD Step 2</fullName>
                </value>
                <value>
                    <fullName>Step 3</fullName>
                </value>
                <value>
                    <fullName>Step 2</fullName>
                </value>
                <value>
                    <fullName>Step 1</fullName>
                </value>
                <value>
                    <fullName>Test Case Step new Flow</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/classes/CaseMgmt_CasePlanController.cls
global class CaseMgmt_CasePlanController {
    @auraEnabled
    public static CaseManager manageCase(Id recordId){
        
        CaseManager caseManagerRecord = new CaseManager();
        List<Id> caseStepIdList = new List<Id>();
        List<Case> caseRecords = new List<Case>([Select Id, Status,Case_Plan__c  From Case where Id =: recordId]);
        if(!caseRecords.isEmpty()){
            caseManagerRecord.CaseStatus = caseRecords[0].Status;
        }
        for(Case_Plan__c casePlan : [Select Id, Status__c, CaseStatusOrdering__c  From Case_Plan__c where Id =: caseRecords[0].Case_Plan__c And Status__c = 'Active']){
            System.debug('SD : Case Plan : ' + casePlan);
            caseManagerRecord.recordCasePlan = casePlan;
        }
        for(Plan_Step__c planStep : [Select Id, Name, Case_Step__c, Case_Plan__c  From Plan_Step__c where Case_Plan__c =: caseManagerRecord.recordCasePlan.Id]){
            caseManagerRecord.listOfPlanSteps.add(planStep);
            caseStepIdList.add(planStep.Case_Step__c);
        }
        for(Case_Step__c caseStep : [Select Id, Start_When__c,Associate_Case_Status__c, IsCompleted__c,Is_Pending__c,Is_Required__c, Name, Flow__c From Case_Step__c where Case__c =: recordId AND Id IN: caseStepIdList AND Associate_Case_Status__c =: caseRecords[0].Status ORDER By CreatedDate ASC ]){
            caseManagerRecord.listOfCaseSteps.add(caseStep);
        }
        
        
        System.debug('SD : Case Record : ' + caseManagerRecord);
        return caseManagerRecord;
    }
    
    
    @InvocableMethod
    public static List<String> fetchRecordTypePicklistValue(List<String> RecordIdList){
        List<String> orderStatusStringList = new List<String>();
        //Map<String, Case_Plan_Support_Process__c> mcs = Case_Plan_Support_Process__c.getAll();
        //Case_Plan_Support_Process__c mc = Case_Plan_Support_Process__c.getValues();
        
        
        //String caserecord =  [Select Id, RecordTypeId from Case where Id IN :  RecordIdList LIMIT 1].RecordTypeId;
        String sfdcURL = URL.getSalesforceBaseUrl().toExternalForm();
        String restAPIURL = sfdcURL + '/services/data/v45.0/ui-api/object-info/Case/picklist-values/' +RecordIdList[0];
        caseMgmt_JSON2Apex myWrapper;
        HttpRequest httpRequest = new HttpRequest();
        httpRequest.setMethod('GET');
        PageReference pg = new PageReference('/Apex/SessionIdUtilityPage');
        String sessionId ='';
        If(!test.isRunningTest()){
            sessionId = pg.getContent().toString().substringBetween('<div id="apiSeesionID">','</div>').trim();
        }
        
        //System.debug('SD: --> ' + pg.getContent().toString());
        System.debug('SD: ' + sessionId);
        httpRequest.setHeader('Authorization', 'OAuth ' + sessionId);
        System.debug('URL >>> ' + restAPIURL);
        httpRequest.setHeader('Authorization', 'Bearer ' + sessionId);
        httpRequest.setEndpoint(restAPIURL);
        String response = '';
        String orderString;
        try {
            If(!test.isRunningTest()){
                Http http = new Http();
                HttpResponse httpResponse = http.send(httpRequest);
                if (httpResponse.getStatusCode() == 200 ) {
                    response = JSON.serializePretty( JSON.deserializeUntyped(httpResponse.getBody()) );
                    caseMgmt_JSON2Apex selectedCse =  caseMgmt_JSON2Apex.parse(httpResponse.getBody());
                    List<caseMgmt_JSON2Apex.values> listOfStatus = selectedCse.picklistFieldValues.Status.Values;
                    for(caseMgmt_JSON2Apex.values value : listOfStatus){
                        if(orderString == null){
                            orderString = String.valueOf(value.value);
                        }else{
                            orderString = orderString + ';' + String.valueOf(value.value);
                        }
                    }
                    orderStatusStringList.add(orderString);
                } else {
                    System.debug(' httpResponse ' + httpResponse.getBody() );
                    throw new CalloutException( httpResponse.getBody() );
                }
            }
        } catch( System.Exception e) {
            System.debug('ERROR: '+ e);
            throw e;
        }
        return orderStatusStringList;
    }
    
    public class CaseManager{
        @auraEnabled public List<Plan_Step__c> listOfPlanSteps;
        @auraEnabled public String CaseStatus;
        @auraEnabled public List<Case_Step__c> listOfCaseSteps;
        @auraEnabled public Case_Plan__c recordCasePlan;
        public CaseManager(){
            listOfCaseSteps = new List<Case_Step__c>();
            listOfPlanSteps = new List<Plan_Step__c>();
            CaseStatus = '';
            recordCasePlan = new Case_Plan__c();
        }
    }
    
}