HelpDesk/src/objects/HelpDesk_Note__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HelpDesk_Ticket__c</fullName>
        <label>HelpDesk Ticket</label>
        <referenceTo>HelpDesk_Ticket__c</referenceTo>
        <relationshipName>HelpDesk_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Help Desk Note</label>
    <nameField>
        <displayFormat>HDN-{00000}</displayFormat>
        <label>Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Desk Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HelpDesk/src/objects/HelpDesk_Ticket__c.object
<CustomObject>
    <label>Help Desk Ticket</label>
    <nameField>
        <displayFormat>HDT-{00000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Desk Tickets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HelpDesk/src/classes/AssembleString.cls
global class AssembleString {
    /**
    * Created by Ashish Pandey on 20/1/19.
    * Method:getAllHelpDeskNotes
    * comment: @InvocableMethod allowed it to be called from cloud flow or PB
    * parameter:parent record Id
    * return:all helpdesk Notes body in a specified format as:
    * 
    * 	Note History
        ---------------
        Created: 12/10/18
        Did some more research and found out foo
        ----------------
        Created: 12/9/18
		Did initial research and found out bar

    */
    
    @InvocableMethod(label='Get Notes Body' description='Returns the list of HelpDeskNotes Body corresponding to the specified Parent IDs.') 
    global static List<string> getAllHelpDeskNotes(List<String> recordId){
        
        List<HelpDesk_Note__c> listOfNotes = new List<HelpDesk_Note__c>();
        listOfNotes=[Select Body__c,CreatedDate from HelpDesk_Note__c where HelpDesk_Ticket__c IN:recordId ORDER BY CreatedDate DESC];
	    List<String> stringOfNotes = new List<String>();
        for(HelpDesk_Note__c item: listOfNotes) {
            stringOfNotes.add(String.valueOf(item.CreatedDate.format()));
            stringOfNotes.add('<br/>');
            stringOfNotes.add(String.valueOf(item.Body__c));
            stringOfNotes.add('<br/>');
            stringOfNotes.add('-----------------------------------');
            stringOfNotes.add('<br/>');
        }
        String result = String.join(stringOfNotes, ', ');
        result = result.replace(',', '');
        return result.split('\n');
    }

}