HelpDesk/src/objects/HelpDesk_Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Question</fullName>
                </value>
                <value>
                    <fullName>Problem</fullName>
                </value>
                <value>
                    <fullName>Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Awaiting Customer Response</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Help Desk Ticket</label>
    <nameField>
        <displayFormat>HDT-{00000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Desk Tickets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HelpDesk/src/classes/HelpDesk_Ticket_Management_Ctrl.cls
global class HelpDesk_Ticket_Management_Ctrl {
    /**
    * Created by 7Summits on 20/1/19.
    * Apex Controller for HelpDesk_Ticket_Management & HelpDeskFLowComponent lightning component
    */
    @AuraEnabled
    global static List < HelpDesk_Ticket__c > fetchHelpDeskTickets() {
        return [ SELECT Id, Name,OwnerId,Owner.Name,Owner.LastName,Category__c, Description__c, Status__c,Subject__c FROM HelpDesk_Ticket__c where Status__c!='Closed'];
    }
    
    @AuraEnabled
    global static List<String> getUserList() {
        List<User> userList=[select Name from User WHERE IsActive = true]; 
        List<String> username = new List<String>();
        for(User u :userList){
            username.add(u.Name);
        }
        return username; 
    }
    @AuraEnabled
    global static String getCurrentUserProfile() {
        Id profileId=userinfo.getProfileId();
        String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
        return profileName;
    }
    @AuraEnabled
    global static void updateOwner(String userName,List<List<String>> ticketIds, List<String> selectedIds) {
        List<String> ids = new List<String>();
        for(List<String> tickets :ticketIds){
            ids.addAll(tickets);
        }
        ids.addAll(selectedIds);
        List<User> userList=[select Id,Name from User WHERE Name =: userName LIMIT 1];
		List<HelpDesk_Ticket__c> helpDesk =[ SELECT Id,OwnerId, Name,Category__c, Description__c, Status__c,Subject__c FROM HelpDesk_Ticket__c where Id IN:ids];
        for(HelpDesk_Ticket__c tickets :helpDesk){
            tickets.OwnerId=userList[0].Id;
            tickets.Status__c='Assigned';
        }
        try{
            if(helpDesk.size()>0){
               update helpDesk;
            }
            
        }catch(Exception e){
            System.debug('Exception e'+e);
        }
        
    }
    @AuraEnabled
    global static void closeTicket(List<List<String>> ticketIds, List<String> selectedId) {
        List<String> ids = new List<String>();
        for(List<String> tickets :ticketIds){
            ids.addAll(tickets);
        }
        ids.addAll(selectedId);
		List<HelpDesk_Ticket__c> helpDesk =[ SELECT Id,Status__c FROM HelpDesk_Ticket__c where Id IN:ids];
        for(HelpDesk_Ticket__c tickets :helpDesk){
            tickets.Status__c='Closed';
        }
        try{
            if(helpDesk.size()>0){
            	update helpDesk;
            }
        }catch(Exception e){
            System.debug('Exception e'+e);
        }
    }
}