HelpDesk/src/objects/HelpDesk_Note__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HelpDesk_Ticket__c</fullName>
        <label>HelpDesk Ticket</label>
        <referenceTo>HelpDesk_Ticket__c</referenceTo>
        <relationshipName>HelpDesk_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Help Desk Note</label>
    <nameField>
        <displayFormat>HDN-{00000}</displayFormat>
        <label>Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Desk Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HelpDesk/src/objects/HelpDesk_Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Question</fullName>
                </value>
                <value>
                    <fullName>Problem</fullName>
                </value>
                <value>
                    <fullName>Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Awaiting Customer Response</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Help Desk Ticket</label>
    <nameField>
        <displayFormat>HDT-{00000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Desk Tickets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HelpDesk/src/classes/AssembleStringTest.cls
@isTest
private class AssembleStringTest{
    @isTest
    static void TestgetAllHelpDeskNotes(){
        Test.startTest();

        HelpDesk_Ticket__c ticket = new HelpDesk_Ticket__c(
          Status__c = 'Closed',          // Status
          Category__c = 'Question',        // Category
          Subject__c = 'Subject3',         // Subject
          Description__c = 'description'  // Description
        );
        insert ticket;
        HelpDesk_Note__c notes = new HelpDesk_Note__c(
          HelpDesk_Ticket__c = ticket.Id,
          Body__c = 'some body goes here'
        );
        insert notes;
        List<String> ticketsIds = new List<String>{ticket.Id};
        AssembleString.getAllHelpDeskNotes(ticketsIds);
        Test.stopTest();
        ticket = [Select Id From HelpDesk_Ticket__c where ID = :ticket.id];
        System.assertNotEquals(null,ticket);
    }
}